import { DatabaseSync } from "node:sqlite";

// Passive, auto-populated observations about the user — the "continuous
// learning" half of Hermes Agent parity (see docs/agent-ia-personnel.md's
// OpenClaw vs Hermes comparison: Hermes builds a user model over time
// without being asked). Deliberately separate from MEMORY.md: that file is
// durable memory the user edits and trusts by hand, this table is the
// model's own unprompted guesses, generated by userModelExtractor.ts after
// each turn. It must never silently merge into MEMORY.md — see CLAUDE.md's
// account of why ULTRON exists at all (an OpenClaw agent taking an
// unreviewed autonomous action). The CLI's `/memory` command is the
// review/purge surface; promoting an observation into MEMORY.md is
// something the user (or ULTRON, asked to do so) does explicitly.

export type ObservationCategory = "preference" | "fact" | "pattern";

export interface UserModelObservation {
  id: number;
  content: string;
  category: ObservationCategory;
  sourceChatId: string;
  createdAt: string;
}

interface ObservationRow {
  id: number;
  content: string;
  category: string;
  source_chat_id: string;
  created_at: string;
}

function toObservation(row: ObservationRow): UserModelObservation {
  return {
    id: row.id,
    content: row.content,
    category: row.category as ObservationCategory,
    sourceChatId: row.source_chat_id,
    createdAt: row.created_at,
  };
}

// Cap on how many observations get injected into the system prompt (see
// renderForPrompt, used by graph.ts's <user_model> block) — the table
// itself keeps everything; only the prompt injection is bounded so it can't
// grow the context window without limit.
const MAX_PROMPT_OBSERVATIONS = 40;

export class UserModelRegistry {
  private db: DatabaseSync;

  constructor(dbPath: string) {
    this.db = new DatabaseSync(dbPath);
    this.db.exec("PRAGMA journal_mode = WAL");
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS user_model_observations (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        content TEXT NOT NULL,
        category TEXT NOT NULL,
        source_chat_id TEXT NOT NULL,
        created_at TEXT NOT NULL
      )
    `);
  }

  add(content: string, category: ObservationCategory, sourceChatId: string): UserModelObservation {
    const now = new Date().toISOString();
    this.db
      .prepare("INSERT INTO user_model_observations (content, category, source_chat_id, created_at) VALUES (?, ?, ?, ?)")
      .run(content, category, sourceChatId, now);
    const row = this.db
      .prepare("SELECT * FROM user_model_observations WHERE id = last_insert_rowid()")
      .get() as unknown as ObservationRow;
    return toObservation(row);
  }

  // Global across every chat — this is a model of the user, not of a single
  // conversation, same reasoning as MEMORY.md being shared everywhere.
  list(limit = 200): UserModelObservation[] {
    const rows = this.db
      .prepare("SELECT * FROM user_model_observations ORDER BY id DESC LIMIT ?")
      .all(limit) as unknown as ObservationRow[];
    return rows.map(toObservation);
  }

  remove(id: number): void {
    this.db.prepare("DELETE FROM user_model_observations WHERE id = ?").run(id);
  }

  clear(): void {
    this.db.exec("DELETE FROM user_model_observations");
  }

  count(): number {
    const row = this.db.prepare("SELECT COUNT(*) as c FROM user_model_observations").get() as { c: number };
    return row.c;
  }

  // Oldest-first so the <user_model> block reads as a timeline, capped to
  // the most recent MAX_PROMPT_OBSERVATIONS.
  renderForPrompt(): string | undefined {
    const rows = this.list(MAX_PROMPT_OBSERVATIONS);
    if (!rows.length) return undefined;
    return rows
      .slice()
      .reverse()
      .map((row) => `- (${row.category}) ${row.content}`)
      .join("\n");
  }
}

let sharedRegistry: UserModelRegistry | undefined;

export function getUserModelRegistry(dbPath: string): UserModelRegistry {
  if (!sharedRegistry) sharedRegistry = new UserModelRegistry(dbPath);
  return sharedRegistry;
}
